### PR TITLE
Video bug fix

### LINKED ISSUE #46: Sending video attachments causes 500s
When making a report from the chatbot, you can attach media and the chatbot will send it via `POST /attachments` to the backend.  Still images work correctly, but videos get dropped on the floor with 500 errors.  Example logs are below:

```
2017-03-26T21:18:24.487973+00:00 app[web.1]: I, [2017-03-26T21:18:24.487919 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] Started POST "/api/v1/attachments?incident_id=813&asset_url=https%3A%2F%2Fvideo.xx.fbcdn.net%2Fv%2Ft42.3356-2%2F17590350_10101361528133511_4008746101254389760_n.mp4%2Fvideo-1490563103.mp4%3Fvabr%3D492977%26oh%3Df379d4a6b8ba3dd0dc1b389dd048ee0c%26oe%3D58DA0590&write_key=[FILTERED]" for 54.159.46.36 at 2017-03-26 21:18:24 +0000
2017-03-26T21:18:24.489051+00:00 app[web.1]: I, [2017-03-26T21:18:24.488999 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] Processing by API::V1::AttachmentsController#create as JSON
2017-03-26T21:18:24.489053+00:00 app[web.1]: D, [2017-03-26T21:18:24.489005 #7] DEBUG -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda]   Role Load (1.8ms)  SELECT  "roles".* FROM "roles" WHERE "roles"."name" = $1 AND "roles"."resource_type" IS NULL AND "roles"."resource_id" IS NULL ORDER BY "roles"."id" ASC LIMIT $2  [["name", "normal"], ["LIMIT", 1]]
2017-03-26T21:18:24.489101+00:00 app[web.1]: I, [2017-03-26T21:18:24.489061 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]   Parameters: {"incident_id"=>"813", "asset_url"=>"https://video.xx.fbcdn.net/v/t42.3356-2/17590350_10101361528133511_4008746101254389760_n.mp4/video-1490563103.mp4?vabr=492977&oh=f379d4a6b8ba3dd0dc1b389dd048ee0c&oe=58DA0590", "write_key"=>"[FILTERED]"}
2017-03-26T21:18:24.491689+00:00 app[web.1]: D, [2017-03-26T21:18:24.491639 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]   APIKey Exists (1.5ms)  SELECT  1 AS one FROM "api_keys" WHERE "api_keys"."write_key" = $1 LIMIT $2  [["write_key", "1553dfb1fed95eecf4cfe2511bec1117"], ["LIMIT", 1]]
2017-03-26T21:18:24.492609+00:00 app[web.1]: D, [2017-03-26T21:18:24.492559 #7] DEBUG -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda]   Role Exists (1.8ms)  SELECT  1 AS one FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND "roles"."id" = $2 LIMIT $3  [["user_id", 192], ["id", 1], ["LIMIT", 1]]
2017-03-26T21:18:24.504970+00:00 app[web.1]: D, [2017-03-26T21:18:24.504910 #7] DEBUG -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda]    (1.6ms)  COMMIT
2017-03-26T21:18:24.509305+00:00 app[web.1]: D, [2017-03-26T21:18:24.509249 #7] DEBUG -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda] [active_model_serializers]   Attachment Load (1.7ms)  SELECT "attachments".* FROM "attachments" WHERE "attachments"."incident_id" = $1  [["incident_id", 813]]
2017-03-26T21:18:24.514677+00:00 app[web.1]: D, [2017-03-26T21:18:24.514621 #7] DEBUG -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda] [active_model_serializers]   Officer Load (1.9ms)  SELECT "officers".* FROM "officers" WHERE "officers"."incident_id" = $1  [["incident_id", 813]]
2017-03-26T21:18:24.515345+00:00 app[web.1]: I, [2017-03-26T21:18:24.515295 #7]  INFO -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda] [active_model_serializers] Rendered IncidentSerializer with ActiveModelSerializers::Adapter::Json (9.75ms)
2017-03-26T21:18:24.515546+00:00 app[web.1]: I, [2017-03-26T21:18:24.515501 #7]  INFO -- : [5000f273-fc81-4f6b-8e4b-07cc7460dcda] Completed 200 OK in 50ms (Views: 6.8ms | ActiveRecord: 21.1ms)
2017-03-26T21:18:24.640108+00:00 app[web.1]: D, [2017-03-26T21:18:24.640032 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] DRAGONFLY: shell command: 'identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170326-11-nittyh.mp4'
2017-03-26T21:18:24.660122+00:00 app[web.1]: W, [2017-03-26T21:18:24.660048 #11]  WARN -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] DRAGONFLY: setting magic attribute for width to nil in <Dragonfly Attachment uid=nil, app=:default> because got error Command failed ('identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170326-11-nittyh.mp4') with exit status 1 and stderr identify.im6: delegate failed `"ffmpeg" -v -1 -i "%i" -vframes %S -vcodec pam -an -f rawvideo -y "%u.pam" 2> "%Z"' @ error/delegate.c/InvokeDelegate/1065.
2017-03-26T21:18:24.660124+00:00 app[web.1]: identify.im6: unable to open image `/tmp/magick-VGW80hgM.pam': No such file or directory @ error/blob.c/OpenBlob/2641.
2017-03-26T21:18:24.660125+00:00 app[web.1]: 
2017-03-26T21:18:24.660289+00:00 app[web.1]: D, [2017-03-26T21:18:24.660240 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] DRAGONFLY: shell command: 'identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170326-11-nittyh.mp4'
2017-03-26T21:18:24.535787+00:00 heroku[router]: at=info method=PATCH path="/api/v1/incidents/813?user_id=192&write_key=1553dfb1fed95eecf4cfe2511bec1117&incident_type_name=citation&start_time=1490400000&rating=1&description=I%20felt%20like%20a%20pool%20of%20cold%20water%20with%20one%20leaf%20floating%20in%20it&latitude=37.748345656973&longitude=-122.17693612467&metadata=%7B%22DATE_OF_INCIDENT%22%3A1490400000%2C%22TIME_OF_INCIDENT%22%3A%225pm%22%2C%22ENCOUNTER_LOCATION%22%3A%22%7B%5C%22lat%5C%22%3A37.748345656973%2C%5C%22long%5C%22%3A-122.17693612467%7D%22%2C%22CONTACT_OUTCOME%22%3A%22citation%22%2C%22CASE_NUMBER%22%3A%229462%22%2C%22INITIAL_CONTACT%22%3A%22got%20stopped%20on%20foot%22%2C%22POLICE_ACTION%22%3A%22other%22%2C%22POLICE_SEARCH%3F%22%3A%22yes%22%2C%22PERMISSION_TO_SEARCH%3F%22%3A%22no%22%2C%22NUMBER_OF_OFFICERS%22%3A%224%22%2C%22OFFICER_NAME%22%3A%22Hambone%20McGillicutty%22%2C%22OFFICER_BADGE_NUMBER%22%3A%226789%22%2C%22OFFICER_RACE%22%3A%22white%2Fcaucasian%22%2C%22OFFICER_GENDER%22%3A%22man%22%2C%22OFFICER_AGE%22%3A%2241-50%22%2C%22OFFICER_DETAILS_DESCRIPTION%22%3A%229%20feet%20tall%2C%20mouth%20full%20of%20corned%20beef%22%2C%22ENCOUNTER_SENTIMENT%22%3A%221%22%2C%22FURTHER_DESCRIPTION%22%3A%22I%20felt%20like%20a%20pool%20of%20cold%20water%20with%20one%20leaf%20floating%20in%20it%22%2C%22USER_REACTION%22%3A%22embarrassed%22%2C%22OFFICER_DISPOSITION%22%3A%22discriminatory%22%7D&reactions_list%5B0%5D=embarrassed&reactions_list%5B1%5D=discriminatory&tags_list%5B0%5D=citation" host=www.raheem.ai request_id=5000f273-fc81-4f6b-8e4b-07cc7460dcda fwd="54.159.46.36" dyno=web.1 connect=1ms service=56ms status=200 bytes=2271 protocol=https
2017-03-26T21:18:24.667315+00:00 app[web.1]: W, [2017-03-26T21:18:24.667260 #11]  WARN -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] DRAGONFLY: setting magic attribute for height to nil in <Dragonfly Attachment uid=nil, app=:default> because got error Command failed ('identify' '-ping' '-format' '%m %w %h' '/tmp/dragonfly20170326-11-nittyh.mp4') with exit status 1 and stderr identify.im6: delegate failed `"ffmpeg" -v -1 -i "%i" -vframes %S -vcodec pam -an -f rawvideo -y "%u.pam" 2> "%Z"' @ error/delegate.c/InvokeDelegate/1065.
2017-03-26T21:18:24.667325+00:00 app[web.1]: identify.im6: unable to open image `/tmp/magick-JtzxxIiQ.pam': No such file or directory @ error/blob.c/OpenBlob/2641.
2017-03-26T21:18:24.667325+00:00 app[web.1]: 
2017-03-26T21:18:24.669410+00:00 app[web.1]: D, [2017-03-26T21:18:24.669360 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]    (1.5ms)  BEGIN
2017-03-26T21:18:24.672495+00:00 app[web.1]: D, [2017-03-26T21:18:24.672445 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]   Incident Load (1.8ms)  SELECT  "incidents".* FROM "incidents" WHERE "incidents"."id" = $1 LIMIT $2  [["id", 813], ["LIMIT", 1]]
2017-03-26T21:18:24.740125+00:00 app[web.1]: D, [2017-03-26T21:18:24.740054 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]    (1.4ms)  ROLLBACK
2017-03-26T21:18:24.740365+00:00 app[web.1]: I, [2017-03-26T21:18:24.740319 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] Completed 500 Internal Server Error in 251ms (ActiveRecord: 6.2ms)
2017-03-26T21:18:24.740459+00:00 app[web.1]: D, [2017-03-26T21:18:24.740418 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Reporting exception: Invalid image file
2017-03-26T21:18:24.768842+00:00 app[web.1]: I, [2017-03-26T21:18:24.768780 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Scheduling item
2017-03-26T21:18:24.768874+00:00 app[web.1]: I, [2017-03-26T21:18:24.768838 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Sending item
2017-03-26T21:18:25.148719+00:00 heroku[router]: at=info method=POST path="/api/v1/attachments?incident_id=813&asset_url=https%3A%2F%2Fvideo.xx.fbcdn.net%2Fv%2Ft42.3356-2%2F17590350_10101361528133511_4008746101254389760_n.mp4%2Fvideo-1490563103.mp4%3Fvabr%3D492977%26oh%3Df379d4a6b8ba3dd0dc1b389dd048ee0c%26oe%3D58DA0590&write_key=1553dfb1fed95eecf4cfe2511bec1117" host=www.raheem.ai request_id=31e84a1e-67ac-4928-94e1-b8ac71f5fa0a fwd="54.159.46.36" dyno=web.1 connect=1ms service=662ms status=500 bytes=243 protocol=https
2017-03-26T21:18:25.144861+00:00 app[web.1]: W, [2017-03-26T21:18:25.144765 #11]  WARN -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Got unexpected status code from Rollbar api: 429
2017-03-26T21:18:25.144913+00:00 app[web.1]: I, [2017-03-26T21:18:25.144851 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Response: {
2017-03-26T21:18:25.144914+00:00 app[web.1]:   "err": 1,
2017-03-26T21:18:25.144915+00:00 app[web.1]:   "message": "Over plan monthly limit. Project id 89859 access token f9cb01305bcf49e4bf4fc42d0ca39338."
2017-03-26T21:18:25.144915+00:00 app[web.1]: }
2017-03-26T21:18:25.144968+00:00 app[web.1]: I, [2017-03-26T21:18:25.144927 #11]  INFO -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Details: https://rollbar.com/instance/uuid?uuid=6c76efac-9f30-4921-8c13-ece1b32289eb (only available if report was successful)
2017-03-26T21:18:25.145023+00:00 app[web.1]: D, [2017-03-26T21:18:25.144983 #11] DEBUG -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] [Rollbar] Exception uuid saved in env: 6c76efac-9f30-4921-8c13-ece1b32289eb
2017-03-26T21:18:25.145800+00:00 app[web.1]: F, [2017-03-26T21:18:25.145753 #11] FATAL -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]   
2017-03-26T21:18:25.145840+00:00 app[web.1]: F, [2017-03-26T21:18:25.145802 #11] FATAL -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] CloudinaryException (Invalid image file):
2017-03-26T21:18:25.145874+00:00 app[web.1]: F, [2017-03-26T21:18:25.145839 #11] FATAL -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a]   
2017-03-26T21:18:25.145938+00:00 app[web.1]: F, [2017-03-26T21:18:25.145878 #11] FATAL -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] app/models/cloudinary_store.rb:5:in `write'
2017-03-26T21:18:25.145972+00:00 app[web.1]: F, [2017-03-26T21:18:25.145936 #11] FATAL -- : [31e84a1e-67ac-4928-94e1-b8ac71f5fa0a] app/controllers/api/v1/attachments_controller.rb:5:in `create'
```

### PR DESCRIPTION
**Pull request by seansu4you87**
closes #46 

See commit log

### CODE REVIEW

**Comment by jhankin** [comment]
Went through review and change process in person

**Comment by kidbombay** [comment]
Removing Dragonfly means no uploads can happen. It's the method in which we process uploads and send to Cloudinary.

**Comment by kidbombay** [comment]
You are only handling media upload with this. There is no support for delete or other methods. This will cost us money then for Cloudinary. Cloudinary store handles all methods required by dragonfly to process images.
All we needed to do was move uploading to background task with Dragonfly.

File: app/controllers/api/v1/attachments_controller.rb [hunk 1]
```diff
@@ -1,13 +1,11 @@
...
-    if @attachment.save
-      render_resource(@attachment)
-    else
-      @errors = @attachment.errors
-      render_errors(@errors, 400)
-    end
+    incident_id = attachment_params[:incident_id]
+    asset_url = attachment_params[:asset_url]
+
+    job_id = AttachmentWorker.perform_async(incident_id, asset_url)
```
Comment (kidbombay) [inline app/controllers/api/v1/attachments_controller.rb]: This isn't right as it only handles the case of uploading. There are other others that can happen with @attachment.save

File: app/jobs/attachment_worker.rb [hunk 2]
```diff
@@ -0,0 +1,13 @@
+class AttachmentWorker
+  include Sidekiq::Worker
+
+  def perform(incident_id, asset_url)
+    incident = Incident.find(incident_id)
+    final_url = MediaService.upload_url(asset_url)
+    Attachment.create!(
+        incident_id: incident_id,
+        url: final_url
```
Comment (kidbombay) [inline app/jobs/attachment_worker.rb]: This is not the way to handle Cloudinary. You save the public id. Then all transforms happen after that.

File: app/controllers/api/v1/attachments_controller.rb (hunk 1 above)
Comment (seansu4you87) [inline app/controllers/api/v1/attachments_controller.rb]: We don't have those use cases as of yet, we can add them in as they come up

**Comment by kidbombay** [comment]
After reviewing, I recommend not merging this.
If the issue is that large video files cause the server to hang (we haven't verified that), there are other fixes.
This breaks core functionality and is huge regression in terms of features.

A simpler fix could just be using a larger dyno size on Heroku as we use the 512MB size right now which is too small for most production rails apps.

File: app/jobs/attachment_worker.rb (hunk 2 above)
Comment (kidbombay) [inline app/jobs/attachment_worker.rb]: It's not. You removed significant functionality beyond just uploading images. And it's not clear what the exact bug was yet.

**Comment by seansu4you87** [comment]
There were two problems with this PR:

1. Videos couldn't upload because the Cloudinary Uploader was broken with video files.  This isn't due to performance or dyno size, but because the code just wasn't right
2. The Dragonfly <> Cloudinary Store integration wasn't working correctly.  Since Cloudinary can take a URL and process that just fine, we didn't have a need for the added complexity that Dragonfly added, given our current use case of the Chatbot just sending us a Facebook URL

**Comment by kidbombay** [comment]
Where is the code not right? There is no different in uploading image or video to cloudinary as far as I know of. What you changed that did help was uploading moved to background job which is less likely to timeout.

File: app/controllers/api/v1/attachments_controller.rb (hunk 1 above)
Comment (kidbombay) [inline app/controllers/api/v1/attachments_controller.rb]: All API controller methods in all rails apps generally work by calling save. Once save returns errors from validation, this is what gets sent in API. You are changing from this pretty standard Rails methodology.

File: app/models/cloudinary_store.rb [hunk 3]
```diff
@@ -1,47 +0,0 @@
-class CloudinaryStore
-
-  # Store the data AND meta, and return a unique string uid
-  def write(content, opts={})
-    result = Cloudinary::Uploader.upload(content.path)
```
Comment (seansu4you87) [inline app/models/cloudinary_store.rb]: @kidbombay this wasn't working, requires an option to be set for video

File: app/services/media_service.rb [hunk 4]
```diff
@@ -0,0 +1,6 @@
+class MediaService
+  def self.upload_url(url)
+    result = Cloudinary::Uploader.upload(url, resource_type: :auto)
```
Comment (seansu4you87) [inline app/services/media_service.rb]: @kidbombay here's the option

**Comment by kidbombay** [comment]
Originally our features with cloudinary is
upload image/file/video
store public id of file (as required by cloudinary api)
store additional methods that dragonfly provides on models that increase rails performance when rendering image metadata (by not requiring reanalysis of image file)
be able to be used in multiple models easily

This change only has
upload image/file video

This is a regression and it's still not clear what the exact video bug is. Moving to a background job would indeed fix a Heroku timeout (likely the culprit) but that can be while still keeping all other features intact extremely easily.

**Comment by seansu4you87** [comment]
@kidbombay there was no Heroku timeout.  It was a straight 500 because the attempt to upload a video to Cloudinary would raise an exception and kill the Puma worker process.  This was evident in our logs, as well as testing this locally.

In terms of storing an ID, I can amend a fix for that and store it, but the Cloudinary url also includes the id within.

Again, not sure how any change we make can be labeled a regression, because literally no one is using our website.  This PR is an attempt to change our API to a state where it is **actually** doing what the chatbot expects it to be doing.

File: app/services/media_service.rb (hunk 4 above)
Comment (kidbombay) [inline app/services/media_service.rb]: Looking into cloudinary docs, but auto option should work for video.
Either way, it would be trivial to change the resource_type in cloudinary_store based on file name.

**Comment by kidbombay** [comment]
If the cloudinary bug is setting the resource type to auto, that's a one line fix in cloudinary store to look for file type and set to video based on that.

**Comment by kidbombay** [comment]
http://cloudinary.com/documentation/image_upload_api_reference#upload - based on the docs because we are using server side uploading, it defaults to image type.
The *only* change we have to make to fix this issue is to change
https://github.com/Raheem-ai/seed_web/blob/c080dd3300febab0f5a12b54ed32525c23b090cb/app/models/cloudinary_store.rb
line 5 to set resource_type to auto.

**Comment by kidbombay** [comment]
Please set
https://github.com/Raheem-ai/seed_web/pull/72 instead.

**Comment by seansu4you87** [comment]
@kidbombay the Dragonfly <> Cloudinary integration was also not working.  Was the original intent on reads for the rails server to download the file from Cloudinary, and then actually serve the bytes of the file to the client?

**Comment by kidbombay** [comment]
What do mean by not working?
Can you point to the code you mean?

**Comment by seansu4you87** [comment]
can you answer my question about original intent?  I'm trying to understand what the shortcomings of this change actually are.

In terms of not working, you'll have to run through the integration yourself.  When actually stepping through, and trying to upload a video end to end, accessing it via the admin panel, etc, things were not working, even after fixing the code to correctly upload a video to Cloudinary.

There is one large advantage of this PR, over what I believe is the previous functionality: The bytes of the video file never touch our server, we simply pass through URLs both on write and on read.

**Comment by kidbombay** [comment]
#68
**Pros**
Video files never touch our server
Fixes bug for video uploads
Background Video Upload

**Cons**
Improper use of Cloudinary API
Delete not supported.
Can't add image files to other models as easily now
Only supports video content
Doesn't use rails conventions for errors/controllers
Narrow in scope.

With #72 
Pros
Fixes Video Bug
Keeps to rails conventions
No other files to be modified.

Cons
Video files go through our server
Foreground Video Upload

We can fix the cons of #72 as an optimization later on. Passing through to cloudinary completely is easily doable and a optimization I like.
As is uploading ANY file in background (not just for attachments)

**Comment by seansu4you87** [comment]
`Improper use of Cloudinary API`
How is this improper?

`Delete not supported.`
When we have delete functionality we need to support, there's nothing stopping us from adding it in

`Can't add image files to other models as easily now`
When that use case comes up, we can easily add that in.  The functionality before this PR also only enables media uploads for one model type.  MediaService is generic, adding media to other models would involve a database migration in the old world as well as the new world.

`Only supports video content`
This does support images and should support any kind of upload

`Doesn't use rails conventions for errors/controllers`
We can change this later if it's causing problems.

`Narrow in scope.`
This is a good thing.  We want something that works for the use cases we have now, not something generic for a product we can't get to because our current product doesn't work.



@kidbombay because this PR works, and we're going to test this out end to end to double check and confirm, and then merge.  All of the cons of this PR can be addressed with followup, if they are actually causing real problems.  Nothing here puts us in a position that we can't back out of.

Because this is **the** launch blocker for the backend side, let's move forward now, and deal with any subsequent shortcomings as they come.

**Comment by kidbombay** [comment]
Don't agree at all.
The other pull #72 fixes the issue as well without any other of the problems. Why don't you try that with the both and see if there's a a problem.

As new developers, you should stick to conventions already established instead of going off on non-rails approved ways. That is true for any project.
